routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/doc', 'ApiController@documentation')->name('doc');
Route::get('/get-books', 'GetBookController@index')->name('get-books');
Route::post('/get_city', 'BookController@get_city')->name('get_city');
Route::get('/api', 'ApiController@api')->name('api');
Route::post('/api', 'ApiController@api')->name('api');
Route::get('/restapi', 'ApiController@index')->name('restapi');
Route::resource('/books', 'BookController');


Route::get('/', 'BookController@index');
Auth::routes();

Route::get('/books', 'BookController@index')->name('books.index');
Route::get('/home', 'BookController@index');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Book extends Model
{
    use SoftDeletes;
    protected $fillable = ['title', 'author_name', 'city', 'file', 'desc', 'country', 'author_last_name', 'creation_year', 'isbn'];

    protected $dates = ['deleted_at'];
//    protected $softDelete = true;
    public function setIsbnAttribute() {
        $pool = '0123456789';
        $this->attributes['isbn'] = substr(str_shuffle(str_repeat($pool, 9)), 0, 9);
    }

}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Countrie;
use App\City;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;


class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('books.index',[
            'books' => Book::paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create',[
            'countries' => Countrie::get(),
        ]);
    }

    public function get_city(Request $request){
        $cities = City::where('country_id',$request->country)->get();
        return response()->json($cities);
    }
    /**
     * Get a validator for an incoming boook request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'title' => 'required|string|max:255|unique:books',
            'author_name' => 'required|string|max:255',
            'author_last_name' => 'required|string',
            'creation_year' => 'required',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->hasFile('file')) {
            $main_image = $request->file('file');
            $file_name = $main_image->getClientOriginalName();
            $destinationPath = public_path('/uploads/books');
            $main_image->move($destinationPath, $file_name);
        }else{
            $file_name = '';
        }
        $this->validator($request->all())->validate();

        Book::create([
            'title' => $request->title,
            'author_name' => $request->author_name,
            'city' => $request->city,
            'country' => $request->country,
            'author_last_name' => $request->author_last_name,
            'creation_year' => $request->creation_year,
            'isbn' => $request->isbn,
            'desc' => $request->desc,
            'file' => $file_name,
        ]);
        return redirect()->route('books.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        return view('books.edit', [
            'countries' => Countrie::get(),
            'citis' => City::where('country_id', $book->country)->get(),
            'book'   => $book,
            'delimiter'  => ''
        ]);
    }

    /**
     * Get a validator for an incoming boook request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */

    protected function editValidator(array $data)
    {
        return Validator::make($data, [
            'title' => 'required|string|max:255',
            'author_name' => 'required|string|max:255',
            'author_last_name' => 'required|string',
            'creation_year' => 'required',
        ]);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $this->editValidator($request->all())->validate();
        if ($request->hasFile('file')) {
            $main_image = $request->file('file');
            $file_name = $main_image->getClientOriginalName();
            $destinationPath = public_path('/uploads/books');
            $main_image->move($destinationPath, $file_name);
        }else{
            $file_name = $book->file;
        }

        $book->update([
            'title' => $request->title,
            'author_name' => $request->author_name,
            'city' => $request->city,
            'country' => $request->country,
            'author_last_name' => $request->author_last_name,
            'creation_year' => $request->creation_year,
            'desc' => $request->desc,
            'isbn' => $request->isbn,
            'file' => $file_name,
        ]);

        return redirect()->route('books.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        Book::where('id',$book->id)->update([
            'deleted_at' => \Carbon\Carbon::now(),
        ]);
        return redirect()->route('books.index');
    }

}

resources/views/books/create.blade.php
@extends('layouts.app')

@section('content')


    <div class="container">
        <hr />
        <form class="form-horizontal book_form" enctype="multipart/form-data" action="{{route('books.store')}}" method="post">
            {{ csrf_field() }}
            <div class="form-group row">
               <label for="title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" id="title" value="{{ old('title') }}">
                    @if ($errors->has('title'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('title') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="isbn" class="col-sm-2 col-form-label">ISBN (Unique value)</label>
                <div class="col-md-10">
                    <input  type="text" class="form-control" placeholder="Automatic generation" id="isbn" name="isbn" value="" readonly="">
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="desc" class="col-sm-2 col-form-label">Description</label>
                <div class="col-md-10">
                    <textarea class="form-control" id="desc" name="desc" rows="3"></textarea>
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="datepicker" class="col-sm-2 col-form-label">Creation Year</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('creation_year') ? ' is-invalid' : '' }}" value="{{ old('creation_year') }}" name="creation_year" id="datepicker">
                    @if ($errors->has('creation_year'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('creation_year') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="author_name" class="col-sm-2 col-form-label">Author Name</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('author_name') ? ' is-invalid' : '' }}" value="{{ old('author_name') }}" id="author_name" name="author_name">
                    @if ($errors->has('author_name'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('author_name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="author_last_name" class="col-sm-2 col-form-label">Author Last Name</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('author_last_name') ? ' is-invalid' : '' }}" value="{{ old('author_last_name') }}" id="author_last_name" name="author_last_name">
                    @if ($errors->has('author_last_name'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('author_last_name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="isbn" class="col-sm-2 col-form-label">Countries</label>
                <div class="col-sm-10">
                    <select class="form-control" data-live-search="true" name="country" id="countries">
                        <option value="">Select Countries</option>
                        @foreach ($countries as $countrie)
                            <option value="{{$countrie->id}}">{{$countrie->country_name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="isbn" class="col-sm-2 col-form-label">Cities</label>
                <div class="col-sm-10">
                    <select class="form-control" data-live-search="true" name="city" id="cities">
                        <option value="">Select Cities</option>
                    </select>
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="file" class="col-sm-2 col-form-label">Image</label>
                <div class="col-md-10 custom-file">
                    <input type="file" name="file" class="custom-file-input" id="file">
                    <label class="custom-file-label" for="file">Choose file...</label>
                </div>
            </div>
            <hr/>
            <div class="form-group row mb-0">
                <div class="col-md-12 text-center">
                    <input class="btn btn-primary" type="submit" value="Save">
                </div>
            </div>
        </form>
    </div>
    <script>
        $('#datepicker').datepicker({
            format: 'yyyy-mm-dd hh:mm:ss',
            uiLibrary: 'bootstrap4'
        });
        $('#countries').on('change', function() {
            var country = this.value;
            $.ajax({
                url: "{{route('get_city')}}",
                type: 'post',
                data: {country:country},
                dataType: 'JSON',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (data) {
                    $('#cities')
                        .find('option')
                        .remove()
                        .end();
                    $.each( data, function( key, value ) {
                        $('#cities').append('<option value="'+value.id+'">'+value.name+'</option>');
                    });
                },
                error: function (data) {

                },
            });
        });

    </script>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <hr />
        <form class="form-horizontal book_form" enctype="multipart/form-data" action="{{route('books.update',$book)}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}
            <div class="form-group row">
                <label for="title" class="col-sm-2 col-form-label">Title</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" id="title" value="{{ $book->title }}">
                    @if ($errors->has('title'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('title') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="isbn" class="col-sm-2 col-form-label">ISBN (Unique value)</label>
                <div class="col-md-10">
                    <input  type="text" class="form-control" placeholder="Automatic generation" id="isbn" name="isbn" value="{{$book->isbn}}" readonly="">
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="desc" class="col-sm-2 col-form-label">Description</label>
                <div class="col-md-10">
                    <textarea class="form-control" id="desc" name="desc" rows="3">{{$book->desc}}</textarea>
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="datepicker" class="col-sm-2 col-form-label">Creation Year</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('creation_year') ? ' is-invalid' : '' }}" value="{{ $book->creation_year }}" name="creation_year" id="datepicker">
                    @if ($errors->has('creation_year'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('creation_year') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="author_name" class="col-sm-2 col-form-label">Author Name</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('author_name') ? ' is-invalid' : '' }}" value="{{ $book->author_name }}" id="author_name" name="author_name">
                    @if ($errors->has('author_name'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('author_name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="author_last_name" class="col-sm-2 col-form-label">Author Last Name</label>
                <div class="col-md-10">
                    <input type="text" class="form-control {{ $errors->has('author_last_name') ? ' is-invalid' : '' }}" value="{{ $book->author_last_name }}" id="author_last_name" name="author_last_name">
                    @if ($errors->has('author_last_name'))
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('author_last_name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="isbn" class="col-sm-2 col-form-label">Countries</label>
                <div class="col-sm-10">
                    <select class="form-control" data-live-search="true" name="country" id="countries">
                        <option value="">Select Countries</option>
                        @foreach ($countries as $countrie)
                            <option
                                    @isset($book->country)
                                            @if ($countrie->id == $book->country)
                                                selected="selected"
                                            @endif
                                    @endisset
                                    value="{{$countrie->id}}">{{$countrie->country_name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="isbn" class="col-sm-2 col-form-label">Cities</label>
                <div class="col-sm-10">
                    <select class="form-control" data-live-search="true" name="city" id="cities">
                        <option value="">Select Cities</option>
                        @foreach ($citis as $city)
                            <option
                                    @isset($book->city)
                                    @if ($city->id == $book->city)
                                    selected="selected"
                                    @endif
                                    @endisset
                                    value="{{$city->id}}">{{$city->name}}</option>
                        @endforeach

                    </select>
                </div>
            </div>
            <hr/>
            <div class="form-group row">
                <label for="file" class="col-sm-2 col-form-label">Image</label>
                <div class="col-md-10 custom-file">
                    <input type="file" name="file" class="custom-file-input" id="file">
                    <label class="custom-file-label" for="file">{{$book->file or 'Choose file...'}}</label>
                    <div class="invalid-feedback">Example invalid custom file feedback</div>
                </div>
            </div>
            <hr/>
            <div class="form-group row mb-0">
                <div class="col-md-12 text-center">
                    <input class="btn btn-primary" type="submit" value="Update">
                </div>
            </div>
        </form>
    </div>
    <script>
        $('#datepicker').datepicker({
            format: 'yyyy-mm-dd hh:mm:ss',
            uiLibrary: 'bootstrap4'
        });
        $('#countries').on('change', function() {
            var country = this.value;
            $.ajax({
                url: "{{route('get_city')}}",
                type: 'post',
                data: {country:country},
                dataType: 'JSON',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (data) {
                    $('#cities')
                        .find('option')
                        .remove()
                        .end();
                    $.each( data, function( key, value ) {
                        $('#cities').append('<option value="'+value.id+'">'+value.name+'</option>');
                    });
                },
                error: function (data) {

                },
            });
        });
    </script>
@endsection

resources/views/books/get.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

    </div>

@endsection

resources/views/books/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <hr>
        <a href="{{route('books.create')}}" class="btn btn-primary pull-right">
            <i class="fa fa-plus-square-o"></i> Create Book
        </a>
        <table class="table table-striped">
            <thead>
            <th>Title</th>
            <th>Author Name</th>
            <th>Author Last Name</th>
            <th>Year of creation</th>
            <th>ISBN</th>
            <th>Country</th>
            <th>City</th>
            <th class="text-right">Action</th>
            </thead>
            <tbody>
            @forelse ($books as $book)
                <?php
                    $country = App\Countrie::where('id', $book->country)->first();
                    $country = json_decode($country, true);
                    $city = App\City::where('id',$book->city)->first();
                    $city = json_decode($city, true);
                ?>
                <tr>
                    <td data-toggle="modal" data-target="#bookModal{{$book->id}}" class="show book_{{$book->id}}" data-id="{{$book->id}}">{{$book->title}}</td>
                    <td data-toggle="modal" data-target="#bookModal{{$book->id}}" class="show book_{{$book->id}}" data-id="{{$book->id}}">{{$book->author_name}}</td>
                    <td data-toggle="modal" data-target="#bookModal{{$book->id}}" class="show book_{{$book->id}}" data-id="{{$book->id}}">{{$book->author_last_name}}</td>
                    <td data-toggle="modal" data-target="#bookModal{{$book->id}}" class="show book_{{$book->id}}" data-id="{{$book->id}}">{{date('d-m-Y', strtotime($book->creation_year))}}</td>
                    <td data-toggle="modal" data-target="#bookModal{{$book->id}}" class="show book_{{$book->id}}" data-id="{{$book->id}}">{{$book->isbn}}</td>
                    <td data-toggle="modal" data-target="#bookModal{{$book->id}}" class="show book_{{$book->id}}" data-id="{{$book->id}}">{{$country['country_name']}}</td>
                    <td data-toggle="modal" data-target="#bookModal{{$book->id}}" class="show book_{{$book->id}}" data-id="{{$book->id}}">{{$city['name']}}</td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Delete ?')){return true}else{return false}" action="{{route('books.destroy',$book)}}" method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field()}}
                            <a class="btn btn-default" href="{{route('books.edit', $book)}}"><i class="fa fa-edit"></i></a>
                            <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
                        </form>
                    </td>
                </tr>
                <div class="modal fade" id="bookModal{{$book->id}}" tabindex="-1" role="dialog" aria-labelledby="bookModal" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">{{$book->title}}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="col-md-12 lib-item" data-category="view">
                                <div class="lib-panel">
                                    <div class="row box-shadow">
                                        <div class="col-md-6">
                                            <img class="lib-img-show" src="/uploads/books/{{$book->file}}">
                                        </div>
                                        <div class="col-md-6">
                                            <div class="lib-row lib-header">
                                                {{$book->author_name}}  {{$book->author_last_name}}
                                                <div class="lib-header-seperator"></div>
                                            </div>
                                            <div class="lib-row lib-desc">
                                                <h4>{{$book->isbn}}</h4>
                                                {{ str_limit($book->desc, 120) }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row box-shadow">
                                        <div class="col-md-12">
                                            <hr/>
                                            <span>{{date('d-m-Y', strtotime($book->creation_year))}}</span>
                                            ||
                                            <span>{{$country['country_name']}} {{$city['name']}}</span>
                                            <hr/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                <tr>
                    <td colspan="12" class="text-center"><h2>No data available</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="12">
                    <ul class="pagination pull-right">
                        {{ $books->links() }}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection